import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Providers } from '@/providers/query';
import { TokenProvider } from "@/providers/token";
import { PreviewProvider } from "@/providers/preview";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <TokenProvider>
            <PreviewProvider>
              {children}
            </PreviewProvider>
          </TokenProvider>
        </Providers>
      </body>
    </html>
  );
}
