import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Providers } from '@/providers/query';
import { TokenProvider } from "@/providers/token";
import { PreviewProvider } from "@/providers/preview";
import { LangProvider } from "@/providers/language";
import { SearchProvider } from "@/providers/search";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <TokenProvider>
            <PreviewProvider>
              <LangProvider>
                <SearchProvider>
                  {children}
                </SearchProvider>
              </LangProvider>
            </PreviewProvider>
          </TokenProvider>
        </Providers>
      </body>
    </html>
  );
}
